export const ruleGuides = [
  ['INVALID_VALUE', 'invalid-directive-value'],
  ['DUP_HOST', 'duplicate-host'],
  ['MISSING_IDENTITY', 'identity-file-exists'],
  ['WILDCARD_ORDER', 'wildcard-host-order'],
  ['WEAK_ALGO', 'deprecated-weak-algorithms'],
  ['DUP_DIRECTIVE', 'duplicate-directives'],
  ['INSECURE_OPT', 'insecure-option'],
  ['UNSAFE_CTRL_PATH', 'unsafe-control-path'],
  ['INCLUDE_CYCLE', 'include-cycle'],
  ['INCLUDE_DEPTH', 'include-depth'],
  ['INCLUDE_READ', 'include-read'],
  ['INCLUDE_GLOB', 'include-glob'],
  ['INCLUDE_NO_MATCH', 'include-no-match'],
  ['NEGATED_HOST', 'negated-only-host'],
  ['PROXY_CONFLICT', 'proxy-command-jump-conflict'],
  ['REVOKED_HOST_KEYS_UNREADABLE', 'revoked-host-keys-readable'],
  ['MISSING_CERTIFICATE', 'certificate-file-exists'],
  ['LOCAL_COMMAND_DISABLED', 'local-command-enabled'],
  ['INVALID_TOKEN', 'invalid-percent-token'],
  ['UNKNOWN_DIRECTIVE', 'unknown-directive'],
  ['DEPRECATED_OPTION', 'deprecated-option'],
  ['CONTROL_PERSIST_UNUSED', 'control-persist-requires-master'],
  ['UPDATE_HOSTKEYS_ASK_PERSIST', 'update-hostkeys-control-persist'],
  ['INVALID_SYNTAX', 'invalid-syntax'],
  ['INVALID_MATCH', 'invalid-match-condition'],
] as const;
